development:
  adapter: postgresql
  encoding: unicode
  database: offers_api_development
  username: shnell
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: offers_api_test
  username: shnell
  password:

production:
  adapter: postgresql
  host: ec2-54-197-238-242.compute-1.amazonaws.com
  encoding: unicode
  database: dap9g5oboe1rgr
  username: bplhiherxlhvau
  port: 5432
  password: F7XbNPbdlPPZj5LgKVRomsxFWV